name: Build package and publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git config --global user.email rafaelfr@outlook.com
          git config --global user.name Rafael Franco
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Generate release
        run: yarn release
      - name: Follow tags
        run: git push --follow-tags origin master
      - name: Publish
        run: |
          NPM_TOKEN=${NPM_TOKEN}
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
          yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
